Erikyvanov/delete edit commnts
AlexOrtegaZ/demos-app pull request #143
Opened 2022-06-17 00:18 UTC by erikyvanov

2022-07-01 00:40 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/member_comment.widget.dart
> +                    ? ReplyButton(onTap: onReplied)
Las personas pueden seguir el hilo de la conversación que se abrió partir de este comentario

2022-07-01 00:40 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/member_comment.widget.dart
> +                    : CommentVotesCount(
Y que te parece si aquí podemos ver los votos que tenia pero no votar

2022-07-04 05:19 UTC, erikyvanov commented on lib/modules/proposals/pages/proposal_comments/widgets/member_comment.widget.dart
> +                    ? ReplyButton(onTap: onReplied)
Eso hace, pero ya cambie el nombre del boton que hace eso, de RepliesCountButton a ShowRepliesButton

2022-07-13 01:36 UTC, AlexOrtegaZ requested changes

2022-07-13 01:36 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/buttons/show_replies_button.widget.dart
> +class ShowRepliesButton extends StatelessWidget {
Renaming this to "ToggleReplySection"

2022-07-13 01:36 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/member_comment.widget.dart
> +                    ? ReplyButton(onTap: onReplied)
Renombrar "ShowRepliesButton" por "ToggleReplySectionButton"

2022-07-13 01:36 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/member_comment.widget.dart
> +                    ? ReplyButton(onTap: onReplied)
Vamos a dejar el botón de Reply cuando el comentario este eliminado

2022-07-13 01:36 UTC, AlexOrtegaZ commented on lib/modules/proposals/pages/proposal_comments/widgets/member_comment.widget.dart
> +                  votesInFavor: comment.upVotesCount,
Crear una propiedad "disabled" en el componente CommentVotesCount

2022-08-03 00:47 UTC, merged