Erikyvanov/user space screen
AlexOrtegaZ/demos-app pull request #57
Opened 2021-11-18 14:40 UTC by erikyvanov

# Pantalla de miembro
![image](https://user-images.githubusercontent.com/44937986/142435463-1ce94655-29fe-4155-a0a8-24ced2a205f9.png)
El tile de Areas, Propuestas y sugerencias es decorativo

![image](https://user-images.githubusercontent.com/44937986/142435590-3750b9eb-a66c-4896-b3c3-ad986d7c7a7c.png)
## Safe widget cuando no se es admistrador
![image](https://user-images.githubusercontent.com/44937986/142435664-ae57fadc-3ac2-41c9-bb78-8a738d6c57d9.png)

![image](https://user-images.githubusercontent.com/44937986/142436359-bdc806c6-e74f-4282-bbf0-1e7c79fc64b1.png)

![image](https://user-images.githubusercontent.com/44937986/142436399-bcf07c1f-0477-44c2-8acf-206097936f95.png)

2021-11-19 19:58 UTC, AlexOrtegaZ requested changes

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/widgets/additional_member_info.widget.dart
> +class AdditionalMemberInfo extends StatelessWidget {
AdditionalMemberInfo no es un buen nombre para un componente que muestra información detallada para usuarios que ya hayan aceptado la invitación.
(es mejor que agregues esta información arriba y agregar a cada campo un if para mostrarlos o no.
Igual podemos discutir este caso.

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/widgets/additional_member_info.widget.dart
> +              MemberProfileField(
No hay que mostrar features a medias o opciones que no van estar funcionando en la próxima entrega.

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/widgets/member_profile_popup_menu_button.widget.dart
> +                  value: 1,
Que es value 1 y 0?

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/shared/services/date_formatter.service.dart
> +      return '';
Podemos regresar el date que nos llega por parámetro

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/members/search/members_search.delegate.dart
> +        future: MemberViewService().findMembersByDisplayName(query),
Que es query?

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/modals/select_role_modal.dart
> +                  title: Text('${getSpaceRoleName(spaceRole)}'),
No necesitas ponerlo en un string aqui, puedes mandar directamente lo que regrese la función

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/modals/select_role_modal.dart
> +  final Function(SpaceRole) updateRol;
Te falto una "e" en "updateRol"

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/member_profile.screen.dart
> +  Future<void> updateRol(SpaceRole newRole) async {
Aqui también falto la "e"

2021-11-19 19:58 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/member_profile.screen.dart
> +    bool newNameIsValid =
Renombra esto a "isNewNameValid" así suena mas a una pregunta

2021-11-24 00:17 UTC, erikyvanov commented on lib/modules/spaces/pages/new_space/screens/members/search/members_search.delegate.dart
> +        future: MemberViewService().findMembersByDisplayName(query),
Query es la propiedad del SearchDelegate donde viene lo que se escribe en el buscador

2021-11-25 21:18 UTC, AlexOrtegaZ requested changes

2021-11-25 21:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/menu_options/cancel_invitation.menuoption.dart
> +void cancelInvitation() {}
El metodo cancelInvitation debería estar implementado en la 10, como lo hacemos en el open

2021-11-25 21:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/menu_options/delete_member.menuoption.dart
> +void deleteMember() {}
deleteMember debería estar implementado en la linea 12

2021-11-25 21:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/widgets/member_profile_popup_menu_button.widget.dart
> +    final MenuOption option = memberIsInvited
Renombra esta opción por deleteOrCancelOption

2021-11-26 14:33 UTC, AlexOrtegaZ approved these changes

2021-11-26 14:33 UTC, merged