Erikyvanov/no proposals
AlexOrtegaZ/demos-app pull request #60
Opened 2021-11-25 16:39 UTC by erikyvanov

![image](https://user-images.githubusercontent.com/44937986/143477780-12b34c9c-c7c2-4190-a088-218fb4117b1b.png)

![image](https://user-images.githubusercontent.com/44937986/143477800-da9d969c-bcb3-4113-b9e6-83fc39a73f2d.png)

2021-11-25 21:13 UTC, AlexOrtegaZ requested changes

2021-11-25 21:13 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/new_space.page.dart
>        Navigator.pushNamed(context, Routes.invitations);
Ya no se esta redirigiéndolas al detalle del espacio al crear un espacio?
El space detail es el que ejecuta esta acción pero no entiendo por que razón se quito

2021-11-25 21:13 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/space_details/spaces_details.page.dart
> +  Future<bool> checkIfCurrentSpaceHasNoRepresentative() async {
En nos nombres trata de no usar negación, esto lo hace un poco confuso para el lector.
el nombre podría ser areAnyRepresentativesOnCurrentSpace
nada mas cambiaria el return
representatives.length != 0

y cuando lo uses ! snapshot.data

2021-11-25 21:13 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/space_details/spaces_details.page.dart
> +        await MemberService().getRepresentatives(space?.spaceId! ?? '');
Si ya estas poniendo que lance una exepcion cuando no ella spaceId el "?? ''" esta sobrado.

2021-11-25 21:13 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/space_details/spaces_details.page.dart
> +            final bool hasNotRepresentative = snapshot.data ?? false;
Puede regresar null?

2021-11-25 21:13 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/spaces/screens/spaces_list/spaces_list.screen.dart
> +        await CurrentSpaceService().setCurrentSpace(spaceView.spaceId);
Aqui tenemos que refactorizar esto, no podemos estar sesteando el current space siempre cuando naveguemos al detalle de espacio, estamos rompiendo el principio de DRY

2021-11-26 03:54 UTC, erikyvanov commented on lib/modules/spaces/pages/spaces/screens/spaces_list/spaces_list.screen.dart
> +        await CurrentSpaceService().setCurrentSpace(spaceView.spaceId);
lo puse en la función goToSpaceDetails

2021-11-26 03:55 UTC, erikyvanov commented on lib/modules/spaces/pages/spaces/screens/spaces_list/spaces_list.screen.dart
> +        await CurrentSpaceService().setCurrentSpace(spaceView.spaceId);
Es necesario que espere el setCurrentSpace porque cuando trataba de entrar a veces no se cumplia el future cuando se estaban renderizando los widgets y se rompia por un null

2021-11-26 14:37 UTC, AlexOrtegaZ approved these changes

2021-11-26 14:37 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/spaces/screens/spaces_list/spaces_list.screen.dart
> +        await CurrentSpaceService().setCurrentSpace(spaceView.spaceId);
ok

2021-11-26 14:38 UTC, merged