Luismeza/hide sliders
AlexOrtegaZ/demos-app pull request #65
Opened 2021-12-03 04:30 UTC by luismeza8

Hay que aceptar primero el pull de edit-space porque este es una subrama de esa rama

2021-12-03 05:18 UTC, AlexOrtegaZ requested changes

2021-12-03 05:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/space_details/screens/space_percentage/space_percentage_settings.screen.dart
> -import 'package:demos_app/modules/spaces/pages/new_space/screens/space_percentages_form/widgets/participation_percentage_slider.widget.dart';
Estos dos componentes los eliminaste?

2021-12-03 05:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/space_percentages_form/widgets/percentage_sliders.widget.dart
> +            onChanged: (participationPercentage) {
Renombra "participationPercentage" por solo "percentage"

2021-12-03 05:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/space_percentages_form/widgets/percentage_sliders.widget.dart
> +                  text: ' para aprobar una de las opciones de la propuesta.'),
En el caso de las aproval_percentage el text decía "para aprobar la propuesta."

Puedes hacer una variable que diga algo así como "toBeApprovedLabel" para que lo mandes desde arriba.

2021-12-03 05:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/space_percentages_form/widgets/percentage_sliders.widget.dart
> +  final String sliderTitle;
Puedes quitarle el prefijo "slider" a "sliderTitle" y al "siliderSubtitle"
Aqui puede quedarse title y subtitle solamente

2021-12-03 05:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/space_percentages_form/widgets/percentage_sliders.widget.dart
> +class PercentageSliders extends StatefulWidget {
Renombra esto a SpacePercentage (sin sliders)

2021-12-03 05:22 UTC, luismeza8 commented on lib/modules/spaces/pages/space_details/screens/space_percentage/space_percentage_settings.screen.dart
> -import 'package:demos_app/modules/spaces/pages/new_space/screens/space_percentages_form/widgets/participation_percentage_slider.widget.dart';
Esos son los widgets de cada slider, entonces como los uni en un solo widget ya no son necesarios

2021-12-03 05:43 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/space_details/screens/space_percentage/space_percentage_settings.screen.dart
> -import 'package:demos_app/modules/spaces/pages/new_space/screens/space_percentages_form/widgets/participation_percentage_slider.widget.dart';
Entonces hay que eliminarlos no?

2021-12-04 18:23 UTC, AlexOrtegaZ approved these changes

2021-12-04 18:23 UTC, merged