Prevent a space from having no administrators
AlexOrtegaZ/demos-app pull request #75
Opened 2021-12-07 22:10 UTC by erikyvanov

![image](https://user-images.githubusercontent.com/44937986/145113911-203f81f1-a856-485c-881a-9ad6f7c46056.png)

2021-12-07 22:18 UTC, AlexOrtegaZ requested changes

2021-12-07 22:18 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/member_profile.screen.dart
> +              content: 'No puedes dejar al espacio sin administrador');
Podemos ponerle como titulo : "No es posible actualizar tu rol."
y contenido: "Es requerido tener al menos un administrador dentro del espacio."

2021-12-07 22:22 UTC, AlexOrtegaZ requested changes

2021-12-07 22:22 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/member_profile.screen.dart
> +      if (widget.member.role == SpaceRole.admin) {
Agrega aqui la validación si soy yo mismo el que se esta modificando y soy administrador
(si soy yo mismo entonces deberia de checar si soy el último, si no no es necesario)

2021-12-08 03:49 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_space/screens/member_profile/member_profile.screen.dart
> +      if (widget.member.role == SpaceRole.admin) {
De hecho podria mostrar la alerta cuando da click en el lapizito, no cuando elijo otro rol ?

2021-12-17 07:24 UTC, erikyvanov commented on lib/modules/spaces/pages/new_space/screens/member_profile/member_profile.screen.dart
> +      if (widget.member.role == SpaceRole.admin) {
Creo que lo de la validacion de si soy administrador no es necesaria a menos de que se quiera mostrar una alerta de si estas seguro dejar de ser admistrador

2021-12-18 19:01 UTC, AlexOrtegaZ approved these changes

2021-12-18 19:01 UTC, merged