title and description of a proposal
AlexOrtegaZ/demos-app pull request #88
Opened 2021-12-31 18:18 UTC by luismeza8

https://user-images.githubusercontent.com/72516745/147835261-bae8113f-c11c-42f3-9970-b352a66a45e7.mp4

2022-01-01 21:28 UTC, AlexOrtegaZ requested changes

2022-01-01 21:28 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_proposal/screens/content_step/content_step.screen.dart
> +  Widget getProposalName() {
Renombra esto a "getProposalNameField"

2022-01-01 21:28 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_proposal/screens/content_step/content_step.screen.dart
> +  Widget getAndShowContent() {
Renombra esto a "getContentField"

2022-01-01 21:28 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_proposal/screens/content_step/content_step.screen.dart
> +  dynamic content;
content debería ser de tipo String

2022-01-01 21:28 UTC, AlexOrtegaZ commented on lib/modules/spaces/pages/new_proposal/screens/content_step/widgets/view_content.widget.dart
> +      focusNode: focusNode,
Para que se ocupa el focusNode, si no se utiliza, se puede remover?

2022-01-01 21:28 UTC, AlexOrtegaZ commented on lib/shared/screens/edit_content.screen.dart
> +  String? content;
content tiene que ser inmutable, trata de quitar el ignore de este componente

2022-01-01 21:28 UTC, AlexOrtegaZ commented on lib/shared/screens/edit_content.screen.dart
> +  AppBar save(BuildContext context) {
esta función no guarda si no que obtiene el AppBar, renombre esto a getAppBar

2022-01-01 23:47 UTC, luismeza8 commented on lib/modules/spaces/pages/new_proposal/screens/content_step/widgets/view_content.widget.dart
> +      focusNode: focusNode,
Sirve para que se enfoque en el evento del teclado, y si es obligatorio
![Screenshot from 2022-01-01 16-35-15](https://user-images.githubusercontent.com/72516745/147862466-cd8b8e18-6644-4e3c-acdd-26a3f660a38c.png)

2022-01-01 23:51 UTC, luismeza8 commented on lib/shared/screens/edit_content.screen.dart
> +  String? content;
lo que pasa es que el controller no puede ser final, entonces necesitaria ser stateful o ponerle la etiqueta ignore

2022-01-05 00:24 UTC, AlexOrtegaZ approved these changes

2022-01-05 00:24 UTC, merged